<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['id' => '1', 'country' => 'Afganistán', 'iso' => 'AF'],
            ['id' => '2', 'country' => 'Albania	', 'iso' => 'AL'],
            ['id' => '3', 'country' => 'Alemania	', 'iso' => 'DE'],
            ['id' => '4', 'country' => 'Andorra	', 'iso' => 'AD'],
            ['id' => '5', 'country' => 'Angola', 'iso' => 'AO'],
            ['id' => '6', 'country' => 'Anguila', 'iso' => 'AI'],
            ['id' => '7', 'country' => 'Antártida', 'iso' => 'AQ'],
            ['id' => '8', 'country' => 'Antigua y Barbuda', 'iso' => 'AG'],
            ['id' => '9', 'country' => 'Arabia Saudita', 'iso' => 'SA'],
            ['id' => '10', 'country' => 'Argelia', 'iso' => 'DZ'],
            ['id' => '11', 'country' => 'Argentina', 'iso' => 'AR'],
            ['id' => '12', 'country' => 'Armenia	', 'iso' => 'AM'],
            ['id' => '13', 'country' => 'Aruba', 'iso' => 'AW'],
            ['id' => '14', 'country' => 'Australia', 'iso' => 'AU'],
            ['id' => '15', 'country' => 'Austria', 'iso' => 'AT'],
            ['id' => '16', 'country' => 'Azerbaiyán', 'iso' => 'AZ'],
            ['id' => '17', 'country' => 'Bahamas	', 'iso' => 'BS'],
            ['id' => '18', 'country' => 'Bahrein', 'iso' => 'BH'],
            ['id' => '19', 'country' => 'Bailía de Guernsey', 'iso' => 'GG'],
            ['id' => '20', 'country' => 'Bangladesh', 'iso' => 'BD'],
            ['id' => '21', 'country' => 'Barbados', 'iso' => 'BB'],
            ['id' => '22', 'country' => 'Belarús', 'iso' => 'BY'],
            ['id' => '23', 'country' => 'Bélgica', 'iso' => 'BE'],
            ['id' => '24', 'country' => 'Belice', 'iso' => 'BZ'],
            ['id' => '25', 'country' => 'Benín', 'iso' => 'BJ'],
            ['id' => '26', 'country' => 'Bermudas', 'iso' => 'BM'],
            ['id' => '27', 'country' => 'Bolivia', 'iso' => 'BO'],
            ['id' => '28', 'country' => 'Brasil', 'iso' => 'BR'],
            ['id' => '29', 'country' => 'Bulgaria', 'iso' => 'BG'],
            ['id' => '30', 'country' => 'Cabo Verde', 'iso' => 'CV'],
            ['id' => '31', 'country' => 'Cambodia', 'iso' => 'KH'],
            ['id' => '32', 'country' => 'Camerún', 'iso' => 'CM'],
            ['id' => '33', 'country' => 'Canadá', 'iso' => 'CA'],
            ['id' => '34', 'country' => 'Catar', 'iso' => 'QA'],
            ['id' => '35', 'country' => 'Chad', 'iso' => 'TD'],
            ['id' => '36', 'country' => 'Chile', 'iso' => 'CL'],
            ['id' => '37', 'country' => 'China', 'iso' => 'CN'],
            ['id' => '38', 'country' => 'Ciudad del Vaticano', 'iso' => 'VA'],
            ['id' => '39', 'country' => 'Colombia', 'iso' => 'CO'],
            ['id' => '40', 'country' => 'Congo', 'iso' => 'CG'],
            ['id' => '41', 'country' => 'Corea del Norte', 'iso' => 'KP'],
            ['id' => '42', 'country' => 'Corea del Sur', 'iso' => 'KR'],
            ['id' => '43', 'country' => 'Costa de Marfil', 'iso' => 'CI'],
            ['id' => '44', 'country' => 'Costa Rica', 'iso' => 'CR'],
            ['id' => '45', 'country' => 'Croacia', 'iso' => 'HR'],
            ['id' => '46', 'country' => 'Cuba', 'iso' => 'CU'],
            ['id' => '47', 'country' => 'Curaçao', 'iso' => 'CW'],
            ['id' => '48', 'country' => 'Dinamarca', 'iso' => 'DK'],
            ['id' => '49', 'country' => 'Dominica', 'iso' => 'DM'],
            ['id' => '50', 'country' => 'Ecuador', 'iso' => 'EC'],
            ['id' => '51', 'country' => 'Egipto', 'iso' => 'EG'],
            ['id' => '52', 'country' => 'El Salvador', 'iso' => 'SV'],
            ['id' => '53', 'country' => 'Emiratos Árabes Unidos', 'iso' => 'AE'],
            ['id' => '54', 'country' => 'Eslovaquia', 'iso' => 'SK'],
            ['id' => '55', 'country' => 'Eslovenia', 'iso' => 'SI'],
            ['id' => '56', 'country' => 'España', 'iso' => 'ES'],
            ['id' => '57', 'country' => 'Estados Unidos', 'iso' => 'US'],
            ['id' => '58', 'country' => 'Estonia', 'iso' => 'EE'],
            ['id' => '59', 'country' => 'Etiopía', 'iso' => 'ET'],
            ['id' => '60', 'country' => 'Fiji', 'iso' => 'FJ'],
            ['id' => '61', 'country' => 'Filipinas', 'iso' => 'PH'],
            ['id' => '62', 'country' => 'Finlandia', 'iso' => 'FI'],
            ['id' => '63', 'country' => 'Francia', 'iso' => 'FR'],
            ['id' => '64', 'country' => 'Georgia', 'iso' => 'GE'],
            ['id' => '65', 'country' => 'Grecia', 'iso' => 'GR'],
            ['id' => '66', 'country' => 'Groenlandia', 'iso' => 'GL'],
            ['id' => '67', 'country' => 'Guatemala', 'iso' => 'GT'],
            ['id' => '68', 'country' => 'Guayana', 'iso' => 'GY'],
            ['id' => '69', 'country' => 'Guayana Francesa', 'iso' => 'GF'],
            ['id' => '70', 'country' => 'Guinea', 'iso' => 'GN'],
            ['id' => '71', 'country' => 'Haití', 'iso' => 'HT'],
            ['id' => '72', 'country' => 'Honduras', 'iso' => 'HN'],
            ['id' => '73', 'country' => 'Hungría', 'iso' => 'HU'],
            ['id' => '74', 'country' => 'India', 'iso' => 'IN'],
            ['id' => '75', 'country' => 'Indonesia', 'iso' => 'ID'],
            ['id' => '76', 'country' => 'Irán', 'iso' => 'IR'],
            ['id' => '77', 'country' => 'Iraq', 'iso' => 'IQ'],
            ['id' => '78', 'country' => 'Irlanda', 'iso' => 'IE'],
            ['id' => '79', 'country' => 'Islandia', 'iso' => 'IS'],
            ['id' => '80', 'country' => 'Israel', 'iso' => 'IL'],
            ['id' => '81', 'country' => 'Italia', 'iso' => 'IT'],
            ['id' => '82', 'country' => 'Jamaica', 'iso' => 'JM'],
            ['id' => '83', 'country' => 'Japón', 'iso' => 'JP'],
            ['id' => '84', 'country' => 'Jordania', 'iso' => 'JO'],
            ['id' => '85', 'country' => 'Kenia', 'iso' => 'KE'],
            ['id' => '86', 'country' => 'Kosovo', 'iso' => 'XK'],
            ['id' => '87', 'country' => 'Líbano', 'iso' => 'LB'],
            ['id' => '88', 'country' => 'Luxemburgo', 'iso' => 'LU'],
            ['id' => '89', 'country' => 'Madagascar', 'iso' => 'MG'],
            ['id' => '90', 'country' => 'Malasia', 'iso' => 'MY'],
            ['id' => '91', 'country' => 'Maldivas', 'iso' => 'MV'],
            ['id' => '92', 'country' => 'Malta', 'iso' => 'MT'],
            ['id' => '93', 'country' => 'Marruecos', 'iso' => 'MA'],
            ['id' => '94', 'country' => 'México', 'iso' => 'MX'],
            ['id' => '95', 'country' => 'Mongolia', 'iso' => 'MN'],
            ['id' => '96', 'country' => 'Nepal', 'iso' => 'NP'],
            ['id' => '97', 'country' => 'Nicaragua', 'iso' => 'NI'],
            ['id' => '98', 'country' => 'Níger', 'iso' => 'NE'],
            ['id' => '99', 'country' => 'Nigeria', 'iso' => 'NG'],
            ['id' => '100', 'country' => 'Noruega', 'iso' => 'NO'],
            ['id' => '101', 'country' => 'Países Bajos', 'iso' => 'NL'],
            ['id' => '102', 'country' => 'Pakistán', 'iso' => 'PK'],
            ['id' => '103', 'country' => 'Palestina', 'iso' => 'PS'],
            ['id' => '104', 'country' => 'Panamá', 'iso' => 'PA'],
            ['id' => '105', 'country' => 'Papúa Nueva Guinea', 'iso' => 'PG'],
            ['id' => '106', 'country' => 'Paraguay', 'iso' => 'PY'],
            ['id' => '107', 'country' => 'Perú', 'iso' => 'PE'],
            ['id' => '108', 'country' => 'Polonia', 'iso' => 'PL'],
            ['id' => '109', 'country' => 'Portugal', 'iso' => 'PT'],
            ['id' => '110', 'country' => 'Puerto Rico', 'iso' => 'PR'],
            ['id' => '111', 'country' => 'Reino Unido', 'iso' => 'GB'],
            ['id' => '112', 'country' => 'República Dominicana', 'iso' => 'DO'],
            ['id' => '113', 'country' => 'Rumania', 'iso' => 'RO'],
            ['id' => '114', 'country' => 'Rusia', 'iso' => 'RU'],
            ['id' => '115', 'country' => 'Senegal', 'iso' => 'SN'],
            ['id' => '116', 'country' => 'Singapur', 'iso' => 'SG'],
            ['id' => '117', 'country' => 'Siria', 'iso' => 'SY'],
            ['id' => '118', 'country' => 'Somalia', 'iso' => 'SO'],
            ['id' => '119', 'country' => 'Sri Lanka', 'iso' => 'LK'],
            ['id' => '120', 'country' => 'Sudáfrica', 'iso' => 'ZA'],
            ['id' => '121', 'country' => 'Sudán', 'iso' => 'SD'],
            ['id' => '122', 'country' => 'Suecia', 'iso' => 'SE'],
            ['id' => '123', 'country' => 'Suiza', 'iso' => 'CH'],
            ['id' => '124', 'country' => 'Tailandia', 'iso' => 'TH'],
            ['id' => '125', 'country' => 'Taiwán', 'iso' => 'TW'],
            ['id' => '126', 'country' => 'Tanzania', 'iso' => 'TZ'],
            ['id' => '127', 'country' => 'Tonga', 'iso' => 'TO'],
            ['id' => '128', 'country' => 'Turquía', 'iso' => 'TR'],
            ['id' => '129', 'country' => 'Ucrania', 'iso' => 'UA'],
            ['id' => '130', 'country' => 'Uruguay', 'iso' => 'UY'],
            ['id' => '131', 'country' => 'Venezuela', 'iso' => 'VE'],
            ['id' => '132', 'country' => 'Vietnam', 'iso' => 'VN'],
            ['id' => '133', 'country' => 'Zambia', 'iso' => 'ZM'],
            ['id' => '134', 'country' => 'Zimbabue', 'iso' => 'ZW']        
        ];
        DB::table('countries')->insert($data);
    }
}
